### ISSUE TITLE
How to using and run demo of the DESERT ？

### ISSUE THREAD

**Issue by Lighting-Zhu** [signetlabdei/DESERT_Underwater#1]
Have a good day！
I have installed the ns-2.35, nsmiracle-master, and the DESERT_Underwater-master in Ubuntu 16.04. Above the installation information of these 3 software, it told me successfully install. But I do not how to run the demo like "test_uwcsmaaloha.tcl". 
I try to use the command line "ns test_uwcsmaaloha.tcl", but it said it needs the file "libMiracle.so" does not found.
Could give me some solutions for using DESERT?  I have read the record which published in "http://telecom.dei.unipd.it/pages/read/58/", but it ooks like it's been an outdated version。
 Thanks

**Comment by fedefava86** [comment]
Hello,
I guess you forgot to source `environment` file in order to setup correctly your `PATH` and `LD_LIBRARY_PATH` env variables. Inside the destination folder you indicated during the installation process, you should find this env file. By issuing
`source environment`
You should then be able to run your samples correctly

**Comment by Lighting-Zhu** [comment]
OK. I will try to do it based on your suggestions. I reset the environment variables that may solve the problem ?
So, there is no fixed order for the installation of ns-2.35, nsmiracle, and DESERT?

I am so sorry that I do not quite understand what you mean. I just got in touch with Ubuntu.

Thanks for your reply. I hope the Desert can be used in my designed modem.

**Comment by fedefava86** [comment]
I don't get the point about the installation order. If you install the framework in this repo using the installer script https://github.com/signetlabdei/DESERT_Underwater/blob/master/DESERT_Framework/install.sh , it will take care of installing all the necessary deps for you (ns, miracle, etc.)
if you installed ns and miracle, manually, it may work but we can't assure this.
Moreover, if you meant to use DESERT together with your custom modem, you will most likely to write your own driver to interact with it.
Please refer to the doxygen documentation for any further doubt you may have https://signetlabdei.github.io/DESERT_Underwater_doc/html/index.html
