### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by alshayokh** [signetlabdei/DESERT_Underwater#10]
![Screenshot from 2024-01-30 12-42-23](https://github.com/signetlabdei/DESERT_Underwater/assets/136689533/8fa014ee-7315-4a0b-b102-e51135aae2d9)
![Screenshot from 2024-01-30 12-49-23](https://github.com/signetlabdei/DESERT_Underwater/assets/136689533/f9398e24-2c7d-48c3-999d-08edf4fda8de)

Hi. I was trying to install the DESERT. But every time I am getting this problem. How can I solve this?

**Comment by fedefava86** [comment]
Hi @alshayokh . This is a problem we discovered lately and is related to gcc-13. We are working on it and we will release at least a work-around soon.

**Comment by fedefava86** [comment]
Hi @alshayokh . We found the issue and we will release it in the next release which will happen soon. If you don't mind, i would close this

**Comment by alshayokh** [comment]
sure.
