### ISSUE TITLE
CSMAALOHA (Throughput, PDR)

### ISSUE THREAD

**Issue by alshayokh** [signetlabdei/DESERT_Underwater#14]
![Screenshot from 2024-02-25 18-58-38](https://github.com/signetlabdei/DESERT_Underwater/assets/136689533/b9b00e2f-1dc5-4098-95cd-ade0c2c12a50)

Hi. I was running the test code of CSMA ALOHA. But I am getting this kind of output. Here for node 0 all the throughput remains same. for node 1 is also like this. What supposed to be the reason? As each link is different, the throughput should be different. Isn't it? Also, I got 104 Packet Delivery ratio in previous run. I do not know whether that is the correct one or not. 

Also, how we can fix the position of the nodes? any suggestion would be helpful.

**Comment by fedefava86** [comment]
This seems not to be a bug, but rather a support request to this is not the right place. The numbers are correct
