### ISSUE TITLE
NAM File Generation

### ISSUE THREAD

**Issue by alshayokh** [signetlabdei/DESERT_Underwater#15]
Hi. Can we generate the NAM file in DESERT? I was trying to run uwdacap.tcl (MAC). But I was not able to get the NAM file. How could we generate the NAM file? Any suggestions would be helpful for me.

**Comment by fedefava86** [comment]
Hi @alshayokh , Thanks for posting this but we  undortunately do not support NAM in desert and we do not plan to do it in the next future.
