### ISSUE TITLE
libMiracle.so: undefined symbol

### ISSUE THREAD

**Issue by joaovictorvolpato** [signetlabdei/DESERT_Underwater#4]
After successfully downloading the framework, I tried running the sample test_desert_woss_dbs.tcl at DESERT_Underwater/DESERT_Framework/DESERT/samples/desert_with_woss_samples with 
"tclsh ./test_desert_woss_dbs.tcl" and it returns the following error 

"couldn't load file "libMiracle.so": /home/joaovolp/lisha/simulations/DESERT_Underwater/DESERT_buildCopy_LOCAL/lib/libMiracle.so: undefined symbol: _ZN9TclObject5traceEP9TracedVar
    while executing
"load libMiracle.so"
    (file "./test_desert_woss_dbs.tcl" line 100)"

Does someone have the same error or know how to fix it?

I'm using Ubuntu22.04 and DESERT 3.3.0

**Comment by fedefava86** [comment]
You should not use tclsh to run your tcl, but use ns 
`ns test_desert_woss_dbs.tcl`
Moreover, remember to source the environment file after the installation (you should have seen it printed at the end of the installation process) 
Finally, the example you are trying to use needs databases to work. Did you downloaded it?

**Comment by joaovictorvolpato** [comment]
Thanks, using ns to run the test worked!
