### ISSUE TITLE
Error loading .so's when running samples (undefined symbol)

### ISSUE THREAD

**Issue by thiagobew** [signetlabdei/DESERT_Underwater#5]
I installed DESERT in development mode using the wizard provided. After successfully installing and executing the source command as instructed, I tried running some samples, but some .so's don't seem to be working/loaded correctly.

Example 1:
"ns test_uwopticalbeampattern.tcl" at DESERT-3.3.0-src/samples/Channel/Optical, with output:
couldn't load file "libuwstaticrouting.so": /home/thiagobew/DESERT_Underwater-master/DESERT_buildCopy_LOCAL/lib/libuwstaticrouting.so: undefined symbol: _ZTI10UWIPModule
    while executing
"load libuwstaticrouting.so"
    (file "test_uwopticalbeampattern.tcl" line 75)

Example 2:
"ns test_polling_backoff.tcl" at DESERT-3.3.0-src/samples/MAC, with output:
couldn't load file "libUwmStd.so": /home/thiagobew/DESERT_Underwater-master/DESERT_buildCopy_LOCAL/lib/libUwmStd.so: undefined symbol: _ZN9MPhy_Bpsk7commandEiPKPKc
    while executing
"load libUwmStd.so"
    (file "test_polling_backoff.tcl" line 82)

I'm using Ubuntu 22.04.1 and DESERT 3.3.0.

**Comment by fedefava86** [comment]
Thanks @thiagobew ,

We are trying to reproduce the problem in our installations, with no luck. We will come back with some more details needed to find the root cause

**Comment by obolo** [comment]
Hello @thiagobew , thanks for reporting.
Could you please provide `pwd` of the test_uwopticalbeampattern.tcl and the result of `cat DESERT_buildCopy_LOCAL/environment`, please? Thank you

**Comment by thiagobew** [comment]
"cat DESERT_buildCopy_LOCAL/environment"
export PATH=/home/thiagobew/DESERT_Underwater-master/DESERT_buildCopy_LOCAL/bin:${PATH}
export LD_LIBRARY_PATH=/home/thiagobew/DESERT_Underwater-master/DESERT_buildCopy_LOCAL/lib:${LD_LIBRARY_PATH}

"pwd"
/home/thiagobew/DESERT_Underwater-master/DESERT_buildCopy_LOCAL/DESERT-3.3.0-src/samples/desert_samples/Channel/Optical

**Comment by obolo** [comment]
We are not able to reproduce your issue. What comes to my mind is that you may have ns2 install via `apt-get install`. If that's the case, please uninstall it, as our OS will find first the ns2 installed via Ubuntu repos, and then the DESERT one is ignored.

**Comment by thiagobew** [comment]
Yes, I did install ns2 before installing DESERT. After removing the Ubuntu one, I just had to reinstall DESERT and the samples ran as expected.

Thank you all for the help!
